sudo: false
language: c
compiler:
    - clang
    - gcc
env:
    global:
        - DUMB_CONSOLE=1
    matrix:
        - COVERAGE=false ASAN=true
        - COVERAGE=false ASAN=false
        - COVERAGE=true  ASAN=false
matrix:
    exclude:
        - env: ASAN=true
          compiler: gcc
install:
    - $COVERAGE && pip install cpp-coveralls || true
script:
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - $ASAN && export CC='clang -O1 -fsanitize=address -g -fno-omit-frame-pointer' || true
    - make hipack-check
after_success:
    - $COVERAGE && coveralls --exclude tools --exclude test --exclude fpconv --gcov-options '\-lp' || true
