language: c
compiler:
    - clang
    - gcc
env:
    - COVERAGE=false
    - COVERAGE=true
install:
    - $COVERAGE && sudo pip install cpp-coveralls || true
script:
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - make hipack-check
after_success:
    - $COVERAGE && coveralls --exclude tools --exclude test --gcov-options '\-lp' || true
