---
name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        persist-credentials: false
    - name: Compile
      run: make -j$(nproc)
    - name: Test
      run: make hipack-check
